language: python
sudo: required
dist: xenial
python:
  - "3.6"
  - "3.7"
allow_failures:
    - python: nightly
    - python: 3.8-dev
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install codecov
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
# command to run tests
script:
  - python3 ChaturbateBot.py -h
after_success:
  - codecov

