language: python
sudo: required
dist: xenial
python:
  - "3.6"
  - "3.7"
allow_failures:
    - python: nightly
    - python: 3.8-dev
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py install
# command to run tests
script:
  - python3 ChaturbateBot.py -h

